name: Build and publish a Docker image to ghcr.io
on:
  push:

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}